http_server:
  port: 5000

logging:
  level: debug
  use_color: true

cameras:
  6B025F7PAJ89E77:
    alias: "Ranger2"
    rotate: 1
    mirror: false
    fix_packet_loss: yes
    audio: true
  BATC609531EXLVS:
    alias: "X5"

# If you are crossing broadcast domains (VLANs) then
# you need to specify all IPs as unicast targets
discovery_ips:
  - 192.168.100.162

# If you are in the same broadcast domain, then
# it's easier to just use the broadcast address of your network
# discovery_ips:
#   - 192.168.100.162

blacklisted_ips:
  - 192.168.40.102
